version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-build:
    executor: aws-cli/default
    working_directory: ~/deployment
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: $PARAM_AWS_CLI_PROFILE_NAME
      - run:
          command: |
            aws configure set aws_access_key_id \
            $PARAM_AWS_CLI_ACCESS_KEY_ID \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS Access Key id
      - run:
          command: |
            aws configure set aws_secret_access_key \
            $PARAM_AWS_CLI_SECRET_ACCESS_KEY \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS Secret Access Key
      - run:
          command: |
            aws configure set region $PARAM_AWS_CLI_REGION \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS default region
      - run:  
          command: | 
            cd source/samples/webclient && npm install
          name: install npm in folder
      - run:  
          command: | 
            cd source/samples/webclient && npm run build
          name: Build files
      - run:  
          command: | 
            aws s3 rm s3://bot-cloudfrontstaticwebsitecloudfronttos3s3bucket-e0bvf7w87v1 --recursive
          name: Remove old website build
      - run:  
          command: | 
            aws s3 sync ./source/samples/webclient/build s3://bot-cloudfrontstaticwebsitecloudfronttos3s3bucket-e0bvf7w87v1 --acl bucket-owner-full-control
          name: Transfer new build to S3 live bucket
      - run:  
          command: |
            aws lexv2-runtime recognize-text --bot-id BW8DKK87PD --bot-alias-id TSTALIASID --locale-id en_US --session-id testbot1234 --text "hello" | grep "Hello, how can I help you?\|Hello, how can I assist you today?\|Hi there, how can I help you today?"
          name: Test Hello Message
      - run:  
          command: |
            aws lexv2-runtime recognize-text --bot-id BW8DKK87PD --bot-alias-id TSTALIASID --locale-id en_US --session-id testbot1234 --text "assignment" | grep "What is the course for the assignment you want more information about?"
          name: Test Assignment 1/3
      - run:  
          command: |
            aws lexv2-runtime recognize-text --bot-id BW8DKK87PD --bot-alias-id TSTALIASID --locale-id en_US --session-id testbot1234 --text "COSC" | grep "What is the assignment number?"
          name: Test Assignment 2/3
      - run:  
          command: |
            aws lexv2-runtime recognize-text --bot-id BW8DKK87PD --bot-alias-id TSTALIASID --locale-id en_US --session-id testbot1234 --text "1" | grep "the course you requested information about does not exist"
          name: Test Assignment 3/3
      - run:  
          command: |
            aws lexv2-runtime recognize-text --bot-id BW8DKK87PD --bot-alias-id TSTALIASID --locale-id en_US --session-id testbot1234 --text "timetable" | grep "At 08:00 you have a tutorial for COSC2413 in Melbourne City at 061.04.023. At 14:30 you have a tutorial for COSC1078 in Melbourne City at 081.06.012."
          name: Test Timetable
      - run:  
         command: |
           aws lexv2-runtime recognize-text --bot-id BW8DKK87PD --bot-alias-id TSTALIASID --locale-id en_US --session-id testbot1234 --text "extension" | grep "Which Course do you need an extension / special consideration?"
         name: Test Extension 1/3
      - run:  
         command: |
           aws lexv2-runtime recognize-text --bot-id BW8DKK87PD --bot-alias-id TSTALIASID --locale-id en_US --session-id testbot1234 --text "COSC2628" | grep "Which Assignment do you need the Extension / Special Consideration?"
         name: Test Extension 2/3
      - run:  
         command: |
           aws lexv2-runtime recognize-text --bot-id BW8DKK87PD --bot-alias-id TSTALIASID --locale-id en_US --session-id testbot1234 --text "1" | grep "You will have to fill the Special Consideration form!"
         name: Test Extension 3/3
workflows:
  aws-cli:
    jobs:
      - aws-cli-build:
          context: aws
