version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-build:
    executor: aws-cli/default
    working_directory: ~/deployment
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: $PARAM_AWS_CLI_PROFILE_NAME
      - run:
          command: |
            aws configure set aws_access_key_id \
            $PARAM_AWS_CLI_ACCESS_KEY_ID \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS Access Key id
      - run:
          command: |
            aws configure set aws_secret_access_key \
            $PARAM_AWS_CLI_SECRET_ACCESS_KEY \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS Secret Access Key
      - run:
          command: |
            aws configure set region $PARAM_AWS_CLI_REGION \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS default region
      - run:  
          command: | 
            cd source/samples/webclient && npm install
          name: install npm in folder
      - run:  
          command: | 
            cd source/samples/webclient && npm run build
          name: Build files
      - run:  
          command: | 
            aws s3 sync ./source/samples/webclient/build s3://bot-cloudfrontstaticwebsitecloudfronttos3s3bucket-e0bvf7w87v1 --acl bucket-owner-full-control
          name: Transfer build to S3 live bucket
      #- run:  
       #   command: | 
        #    aws cloudformation create-stack \
         #   --stack-name rmitbot$CIRCLE_BUILD_NUM \
          #  --template-url "s3://rmitbot33/rmitbot33/0.0.33/serverless-bot-framework.template"
        #  name: Create cloudformation stack
     # - run:  
     #     command: | 
     #       aws s3 rb s3://rmitbot$CIRCLE_BUILD_NUM/rmitbot$CIRCLE_BUILD_NUM/0.0.$CIRCLE_BUILD_NUM --force
     #     name: Delete temp bucket 1
     # - run:  
     #     command: | 
     #       aws s3 rb s3://rmitbot$CIRCLE_BUILD_NUM-ap-southeast-2/rmitbot$CIRCLE_BUILD_NUM/0.0.$CIRCLE_BUILD_NUM --force
     #     name: Delete temp bucket 2

        


workflows:
  aws-cli:
    jobs:
      - aws-cli-build:
          context: aws
