version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: pwd
      - run: ls
      - run: cd ..
      - run: ls
      - run: pwd
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
