version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    working_directory: ~/deployment
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: $PARAM_AWS_CLI_PROFILE_NAME
      - run:
          command: |
            aws configure set aws_access_key_id \
            $PARAM_AWS_CLI_ACCESS_KEY_ID \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS Access Key id
      - run:
          command: |
            aws configure set aws_secret_access_key \
            $PARAM_AWS_CLI_SECRET_ACCESS_KEY \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS Secret Access Key
      - run:
          command: |
            aws configure set region $PARAM_AWS_CLI_REGION \
            --profile $PARAM_AWS_CLI_PROFILE_NAME
          name: Configure AWS default region
      - run: aws configure list
      - run: cd deployment && chmod +x ./build-s3-dist.sh
      - run: cd deployment && ./build-s3-dist.sh RMITBOT$CIRCLE_BUILD_NUM RMITBOT$CIRCLE_BUILD_NUM 0.0.$CIRCLE_BUILD_NUM
      - run: aws s3 mb s3://RMITBOT$CIRCLE_BUILD_NUM --region ap-southeast-2
      - run: aws s3 mb s3://RMITBOT$CIRCLE_BUILD_NUM-ap-southeast-2 --ap-southeast-2
      - run: aws s3 sync ./deployment/global-s3-assets s3://RMITBOT$CIRCLE_BUILD_NUMM/RMITBOT$CIRCLE_BUILD_NUM/0.0.$CIRCLE_BUILD_NUM --acl bucket-owner-full-control
      - run: aws s3 sync ./deployment/regional-s3-assets s3://RMITBOT$CIRCLE_BUILD_NUM-us-east-1/RMITBOT$CIRCLE_BUILD_NUM/0.0.$CIRCLE_BUILD_NUM --acl bucket-owner-full-control
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
