version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    working_directory: ~/deployment
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: cd deployment && chmod +x ./build-s3-dist.sh
      - run: cd deployment && ./build-s3-dist.sh $CIRCLE_BUILD_NUM $CIRCLE_BUILD_NUM $CIRCLE_BUILD_NUM
      - run: aws s3 mb s3://$CIRCLE_BUILD_NUM --region ap-southeast-2
      - run: aws s3 mb s3://$CIRCLE_BUILD_NUM-ap-southeast-2 --ap-southeast-2
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
