version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: pwd
      - run: ls
      - run: cd deployment
      - run: ls -r
      - run: pwd
      - run: chmod +x deployment/build-s3-dist.sh
      - run: deployment/build-s3-dist.sh $CIRCLE_BUILD_NUM $CIRCLE_BUILD_NUM $CIRCLE_BUILD_NUM
workflows:
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
